Add frontend-all job to validate frontend tests
Add a job to check the results of frontend jobs.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -101,6 +101,19 @@ jobs:
       - name: Run frontend tests
         working-directory: ./frontend
         run: pnpm run test
+        
+  frontend-all:
+    needs: [frontend-build, frontend-checks]
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check all frontend jobs passed
+        run: |
+          if [[ "${{ needs.frontend-build.result }}" != "success" || "${{ needs.frontend-checks.result }}" != "success" ]]; then
+            echo "One or more frontend jobs failed"
+            exit 1
+          fi
+
 
   go-tests:
     needs: frontend-build
